---
- hosts: test
  name: uninstall apache
  become: yes
  tasks:
        - name: stop apache
          service:
            name: httpd
            state: stopped
        - name: unistall httpd
          package:
            name: httpd
            state: absent       
