---
  - name: apache
    hosts: test
    tasks:
      - name: prova
        yum:
          name: squid
          state: latest
      - name: start squid
        service:
          name: squid
          state: started
          enabled: True
      - name: disable firewalld
        service:
          name: firewalld
          state: stopped
          enabled: False
